import type { divergenciasType } from "../types/types"

export const divergenciasData: divergenciasType[] = [
  {
    id: "DV-1",
    store: "101",
    supplier: "Distribuidora ABC",
    EntryDate: new Date("2025-06-10"),
    supplierDocument: "12.345.678/0001-90",
    openDays: 5,
    status: "PENDENTE",
    produtos: [
      {
        productCode: "A123",
        quantity: 3,
        value: 150.5,
        type: "FALTA",
        entryNote: 1001,
      },
    ],
    description: "Produto faltando na remessa.",
  },
  {
    id: "DV-2",
    store: "101",
    supplier: "Fornecedor XYZ",
    EntryDate: new Date("2025-06-12"),
    supplierDocument: "98.765.432/0001-10",
    openDays: 3,
    status: "APROVADO",
    produtos: [
      {
        productCode: "B456",
        quantity: 1,
        value: 80,
        type: "AVARIA",
        entryNote: 1002,
      },
    ],
    description: "Produto chegou danificado.",
  },
  {
    id: "DV-3",
    store: "102",
    supplier: "Importadora BR",
    EntryDate: new Date("2025-10-06"),
    supplierDocument: "11.222.333/0001-44",
    openDays: 10,
    status: "PENDENTE",
    produtos: [
      {
        productCode: "C789",
        quantity: 5,
        value: 42.99,
        type: "SOBRA",
        entryNote: 1003,
      },
    ],
    description: "Enviado mais produtos do que solicitado.",
  },
  {
    id: "DV-4",
    store: "103",
    supplier: "Tech Fornecedora",
    EntryDate: new Date("2025-06-08"),
    supplierDocument: "00.111.222/0001-33",
    openDays: 7,
    status: "PENDENTE",
    produtos: [
      {
        productCode: "D321",
        quantity: 2,
        value: 99.99,
        type: "OUTRO",
        entryNote: 1004,
      },
    ],
    description: "Divergência de documentação.",
  },
  {
    id: "DV-5",
    store: "104",
    supplier: "Log Distribuição",
    EntryDate: new Date("2025-06-03"),
    supplierDocument: "77.888.999/0001-55",
    openDays: 12,
    status: "PENDENTE",
    produtos: [
      {
        productCode: "E654",
        quantity: 10,
        value: 25,
        type: "FALTA",
        entryNote: 1005,
      },
    ],
    description: "Itens não entregues.",
  },
  {
    id: "DV-6",
    store: "101",
    supplier: "Distribuidora ABC",
    EntryDate: new Date("2025-06-11"),
    supplierDocument: "12.345.678/0001-90",
    openDays: 4,
    status: "APROVADO",
    produtos: [
      {
        productCode: "F987",
        quantity: 2,
        value: 65.3,
        type: "AVARIA",
        entryNote: 1006,
      },
    ],
    description: "Caixa amassada e produto com defeito.",
  },
  {
    id: "DV-7",
    store: "101",
    supplier: "Fornecedor XYZ",
    EntryDate: new Date("2025-06-11"),
    supplierDocument: "98.765.432/0001-10",
    openDays: 14,
    status: "PENDENTE",
    produtos: [
      {
        productCode: "G432",
        quantity: 1,
        value: 310,
        type: "OUTRO",
        entryNote: 1007,
      },
    ],
    description: "Faltou nota fiscal anexa.",
  },
  {
    id: "DV-8",
    store: "102",
    supplier: "Importadora BR",
    EntryDate: new Date("2025-06-11"),
    supplierDocument: "11.222.333/0001-44",
    openDays: 1,
    status: "PENDENTE",
    produtos: [
      {
        productCode: "H111",
        quantity: 6,
        value: 12.5,
        type: "FALTA",
        entryNote: 1008,
      },
    ],
    description: "Quantidade menor entregue.",
  },
  {
    id: "DV-9",
    store: "103",
    supplier: "Tech Fornecedora",
    EntryDate: new Date("2025-06-11"),
    supplierDocument: "00.111.222/0001-33",
    openDays: 2,
    status: "PENDENTE",
    produtos: [
      {
        productCode: "I222",
        quantity: 3,
        value: 55.75,
        type: "SOBRA",
        entryNote: 1009,
      },
    ],
    description: "Remessa maior do que o pedido.",
  },
  {
    id: "DV-10",
    store: "104",
    supplier: "Log Distribuição",
    EntryDate: new Date("2025-06-11"),
    supplierDocument: "77.888.999/0001-55",
    openDays: 13,
    status: "APROVADO",
    produtos: [
      {
        productCode: "J333",
        quantity: 4,
        value: 40,
        type: "AVARIA",
        entryNote: 1010,
      },
    ],
    description: "Produto com embalagem rasgada.",
  },
]
