import type { divergenciasType } from "../types/types"

export const divergenciasData: divergenciasType[] = [
  {
    id: "2025001",
    store: "101",
    date: new Date("2025-10-01"),
    days_remaining: new Date("2025-10-01").getDate() - new Date().getDate(),
    supplier: "Fornecedor A",
    sales_invoice: "NFV001",
    status: "Pendente",
    description: "Compra de materiais de escritório",
  },
  {
    id: "2025002",
    store: "102",
    date: new Date("2025-10-02"),
    days_remaining: new Date("2025-10-02").getDate() - new Date().getDate(),
    supplier: "Fornecedor B",
    sales_invoice: "NFV002",
    status: "Aprovada",
    description: "Compra de equipamentos de informática",
  },
  {
    id: "2025003",
    store: "103",
    date: new Date("2025-10-03"),
    days_remaining: new Date("2025-10-03").getDate() - new Date().getDate(),
    supplier: "Fornecedor C",
    sales_invoice: "NFV003",
    status: "Rejeitada",
    description: "Compra de móveis para escritório",
  },
  {
    id: "2025004",
    store: "101",
    date: new Date("2025-10-04"),
    days_remaining: new Date("2025-10-04").getDate() - new Date().getDate(),
    supplier: "Fornecedor D",
    sales_invoice: "NFV004",
    status: "Pendente",
    description: "Compra de suprimentos de limpeza",
  },
  {
    id: "2025005",
    store: "102",
    date: new Date("2025-10-05"),
    days_remaining: new Date("2025-10-05").getDate() - new Date().getDate(),
    supplier: "Fornecedor E",
    sales_invoice: "NFV005",
    status: "Aprovada",
    description: "Compra de materiais de construção",
  },
  {
    id: "2025006",
    store: "103",
    date: new Date("2025-10-06"),
    days_remaining: new Date("2025-10-06").getDate() - new Date().getDate(),
    supplier: "Fornecedor F",
    sales_invoice: "NFV006",
    status: "Rejeitada",
    description: "Compra de equipamentos de segurança",
  },
]
