import type { garantiasType } from "../types/types"

export const garantiasData: garantiasType[] = [
  {
    id: "GA-1",
    store: "101",
    requestDate: new Date("2025-10-01"),
    openDays: new Date("2025-10-01").getDate() - new Date().getDate(),
    supplier: "Fornecedor A",
    salesNote: "NFV001",
    status: "NOVO",
    produtos: [
      {
        productCode: "A123",
        quantity: 3,
        value: 150.5,
      },
      {
        productCode: "A124",
        quantity: 4,
        value: 154.5,
      },
    ],
    description: "Compra de materiais de escritório",
  },
  {
    id: "GA-2",
    store: "102",
    requestDate: new Date("2025-10-02"),
    openDays: new Date("2025-10-02").getDate() - new Date().getDate(),
    supplier: "Fornecedor B",
    salesNote: "NFV002",
    status: "RESOLVIDO",
    produtos: [
      {
        productCode: "B456",
        quantity: 1,
        value: 80,
      },
    ],
    description: "Compra de equipamentos de informática",
  },
  {
    id: "GA-3",
    store: "103",
    requestDate: new Date("2025-10-03"),
    openDays: new Date("2025-10-03").getDate() - new Date().getDate(),
    supplier: "Fornecedor C",
    salesNote: "NFV003",
    status: "CANCELADO",
    produtos: [
      {
        productCode: "B456",
        quantity: 1,
        value: 80,
      },
    ],
    description: "Compra de móveis para escritório",
  },
  {
    id: "GA-4",
    store: "101",
    requestDate: new Date("2025-10-04"),
    openDays: new Date("2025-10-04").getDate() - new Date().getDate(),
    supplier: "Fornecedor D",
    salesNote: "NFV004",
    status: "PENDENTE",
    produtos: [
      {
        productCode: "D321",
        quantity: 2,
        value: 99.99,
      },
    ],
    description: "Compra de suprimentos de limpeza",
  },
  {
    id: "GA-5",
    store: "102",
    requestDate: new Date("2025-10-05"),
    openDays: new Date("2025-10-05").getDate() - new Date().getDate(),
    supplier: "Fornecedor E",
    salesNote: "NFV005",
    status: "RESOLVIDO",
    produtos: [
      {
        productCode: "E654",
        quantity: 10,
        value: 25,
      },
    ],
    description: "Compra de materiais de construção",
  },
  {
    id: "GA-6",
    store: "103",
    requestDate: new Date("2025-10-06"),
    openDays: new Date("2025-10-06").getDate() - new Date().getDate(),
    supplier: "Fornecedor F",
    salesNote: "NFV006",
    status: "CANCELADO",
    produtos: [
      {
        productCode: "F987",
        quantity: 2,
        value: 65.3,
      },
    ],
    description: "Compra de equipamentos de segurança",
  },
  {
    id: "GA-7",
    store: "104",
    requestDate: new Date("2025-10-07"),
    openDays: new Date("2025-10-07").getDate() - new Date().getDate(),
    supplier: "Fornecedor G",
    salesNote: "NFV007",
    status: "NOVO",
    produtos: [
      {
        productCode: "G111",
        quantity: 5,
        value: 300,
      },
      {
        productCode: "G112",
        quantity: 2,
        value: 120.25,
      },
    ],
    description: "Aquisição de software de gestão",
  },
  {
    id: "GA-8",
    store: "101",
    requestDate: new Date("2025-10-08"),
    openDays: new Date("2025-10-08").getDate() - new Date().getDate(),
    supplier: "Fornecedor H",
    salesNote: "NFV008",
    status: "PENDENTE",
    produtos: [
      {
        productCode: "H222",
        quantity: 8,
        value: 45.5,
      },
    ],
    description: "Manutenção de ar condicionado",
  },
  {
    id: "GA-9",
    store: "105",
    requestDate: new Date("2025-10-09"),
    openDays: new Date("2025-10-09").getDate() - new Date().getDate(),
    supplier: "Fornecedor I",
    salesNote: "NFV009",
    status: "RESOLVIDO",
    produtos: [
      {
        productCode: "I333",
        quantity: 1,
        value: 1200,
      },
    ],
    description: "Compra de smartphone para diretoria",
  },
  {
    id: "GA-10",
    store: "102",
    requestDate: new Date("2025-10-10"),
    openDays: new Date("2025-10-10").getDate() - new Date().getDate(),
    supplier: "Fornecedor J",
    salesNote: "NFV010",
    status: "NOVO",
    produtos: [
      {
        productCode: "J444",
        quantity: 20,
        value: 15.99,
      },
    ],
    description: "Compra de uniformes para equipe",
  },
  {
    id: "GA-11",
    store: "103",
    requestDate: new Date("2025-10-11"),
    openDays: new Date("2025-10-11").getDate() - new Date().getDate(),
    supplier: "Fornecedor A",
    salesNote: "NFV011",
    status: "PENDENTE",
    produtos: [
      {
        productCode: "A125",
        quantity: 6,
        value: 75,
      },
    ],
    description: "Reposição de estoque de canetas e papéis",
  },
  {
    id: "GA-12",
    store: "104",
    requestDate: new Date("2025-10-12"),
    openDays: new Date("2025-10-12").getDate() - new Date().getDate(),
    supplier: "Fornecedor K",
    salesNote: "NFV012",
    status: "CANCELADO",
    produtos: [
      {
        productCode: "K555",
        quantity: 3,
        value: 250,
      },
    ],
    description: "Contratação de serviço de buffet para evento",
  },
  {
    id: "GA-13",
    store: "101",
    requestDate: new Date("2025-10-13"),
    openDays: new Date("2025-10-13").getDate() - new Date().getDate(),
    supplier: "Fornecedor L",
    salesNote: "NFV013",
    status: "RESOLVIDO",
    produtos: [
      {
        productCode: "L666",
        quantity: 1,
        value: 2500,
      },
      {
        productCode: "L667",
        quantity: 5,
        value: 89.9,
      },
    ],
    description: "Compra de projetor e acessórios",
  },
  {
    id: "GA-14",
    store: "105",
    requestDate: new Date("2025-10-14"),
    openDays: new Date("2025-10-14").getDate() - new Date().getDate(),
    supplier: "Fornecedor M",
    salesNote: "NFV014",
    status: "NOVO",
    produtos: [
      {
        productCode: "M777",
        quantity: 12,
        value: 12.5,
      },
    ],
    description: "Compra de produtos de copa e cozinha",
  },
  {
    id: "GA-15",
    store: "102",
    requestDate: new Date("2025-10-15"),
    openDays: new Date("2025-10-15").getDate() - new Date().getDate(),
    supplier: "Fornecedor B",
    salesNote: "NFV015",
    status: "PENDENTE",
    produtos: [
      {
        productCode: "B457",
        quantity: 4,
        value: 180,
      },
    ],
    description: "Upgrade de memória RAM para computadores",
  },
]
